backend/src/components/notification.js

Add pageSize to GET Notifications to raise the max number of records in GET response payload (new limit = 500 records)

ofmcc-1001 - add pageSize to GET Notifications request

---

frontend/src/components/licences/LicenceDetails.vue

Hide error message for missing Split Classroom description in LicenceDetails for readonly mode

ofmcc-1832 - hide error message for missing Split Classroom description in LicenceDetails for readonly mode

---

frontend/src/stores/auth.js

Internal users weren't able to login with new permissions framework. Added fix. Full Impersonate functionality is pending.

Fixed issues with errors on login/navigation.

---

frontend/src/components/applications/CancelApplicationDialog.vue
frontend/src/components/reports/ReportingSearchCard.vue
frontend/src/utils/constants.js
frontend/src/views/applications/ApplicationsHistoryView.vue

In Application History page:
- For Core application, display Verified status as “In Review”
- If the user cancels a Core application from the Portal, that application will be deactivated in CRM and set to “Cancelled by SP” in CRM
- If the user cancels a Supplementary application from the Portal, that application will be deactivated in CRM and set to “Cancelled” in CRM

ofmcc-1874 - update Application/Supp App status mapping

---

frontend/src/views/MessagingView.vue

Note, the consensus was that the count is legitimately different since the header indicates every that needs to be addressed including Action Required and unread notifications/messages. For clarity, the tab counts were updated to indicate that the count only refers to unread notifications/messages.

OFMCC-1363 - Messages unread label

---

backend/src/components/fundingAgreements.js
frontend/src/services/fundingAgreementService.js
frontend/src/views/supp-allowances/SupplementaryAllowanceView.vue
frontend/src/views/supp-allowances/SupplementarySubmitView.vue

-- removed function getActiveFundingAgreementByFacilityId(facilityId) as it does not appear to be used anywhere 
always return the newest version (either the original Funding Agreement or MOD) that is active, unless being used for Supp Apps, in which case return the original FA. This is being updated here to support the backdate Transport App functionality (ofm 4772)

update Funding Agreements to always return the newest FA or MOD

---

.github/workflows/deploy-to-openshift-backend-dev.yml
.github/workflows/deploy-to-openshift-backend-test.yml
.github/workflows/deploy-to-openshift-backend-uat.yml
.github/workflows/deploy-to-openshift-frontend-test.yml
.github/workflows/deploy-to-openshift-frontend-uat.yml

OpenShift cli needs a newer version of GCC in order to work.  We have updated the Ubuntu container for deployment to the latest LTS (24.04)

fix: breaking changes from 4.16

---

frontend/src/components/messages/NewRequestDialog.vue
frontend/src/views/account-mgmt/ManageFacilityView.vue
frontend/src/views/account-mgmt/ManageOrganizationView.vue

- Added emit to allow logic on close. For Facility/Org this means we can refresh the data
- I did not leverage the custom navigation logic added by Viet as I didn't want to impact the existing functionality of the screen. Also the "Return to foo" button label won't work for these screen titles.

OFMCC-3478 - Handle refresh issue

---

backend/src/components/logger.js

Reduces the amount of noise we get in our logfiles, which is more than 2.5mb per day.

feat: remove 200 response health checks from log

---

backend/package-lock.json
backend/package.json
backend/src/routes/auth.js

Update express-validator to version 7.1.0 to get checkEmpty support.
Added checkEmpty/checkEmpty to /auth/refresh.

OFMCC-5349 - Address WAVA API Mass Assignment

---

frontend/src/components/messages/MessagesTab.vue
frontend/src/components/messages/RequestConversations.vue
frontend/src/components/notifications/NotificationDetails.vue
frontend/src/components/notifications/NotificationsTab.vue
testing/README.md
testing/cypress/e2e/2-portal-dashboard-and-communications/assistance_request.cy.js
testing/cypress/e2e/3-application-intake/core_application.cy.js

Changed message button CSS on focus to not have the tiny bit of blue background 
Added back in the "Reply" button functionality that was mistakenly removed from a previous PR
Added <span> tags on messaging buttons, so whitespace would no longer be underlined 
I left 'Notifications' and 'Messages' tab words bold - as I think they look better but open to suggestions on this

small ui fixes and reply button replies again

---

frontend/src/components/supp-allowances/TransportationAllowance.vue
frontend/src/utils/rules.js
frontend/src/views/supp-allowances/SupplementaryFormView.vue

Changed the messaging in 'rules' for the min value -- currently this PR is the only files that use that error message, so I don't think there should be an impact there 
Prevent save / next if user enters '0' on some fields on Transport App. I purposefully did not set the 'min' value on format to 1 - because it becomes annoying if a user wants to type in a different number that does not start with one. 
Works with both current and next year scenarios

Ofmcc 5789 transport validation enhancement

---

backend/src/components/applications.js
backend/src/util/mapping/Mappings.js
frontend/src/components/messages/NewRequestDialog.vue
frontend/src/components/supp-allowances/IndigenousProgrammingAllowance.vue
frontend/src/components/supp-allowances/SupportNeedsProgrammingAllowance.vue
frontend/src/components/supp-allowances/TransportationAllowance.vue
frontend/src/services/applicationService.js
frontend/src/utils/constants.js
frontend/src/utils/constants/suppConstants.js
frontend/src/views/applications/ApplicationConfirmationView.vue
frontend/src/views/applications/ApplicationsHistoryView.vue
frontend/src/views/applications/SelectFacilityView.vue
frontend/src/views/supp-allowances/SupplementaryAllowanceView.vue
frontend/src/views/supp-allowances/SupplementaryConfirmation.vue
frontend/src/views/supp-allowances/SupplementaryFormView.vue
frontend/src/views/supp-allowances/SupplementarySubmitView.vue

- Add Redirected Applications to App History Table 
- Show / Hide Supp apps/ Irregular expenses based on union/ family flags 
- Wording updates that I missed on the Supp Apps page
- Filter Supp Apps / Irreg Expense dropdowns to only include eligible facilities -
** note- in some places I call getFacility, in others I look at the answer on the applications to check for the isUnionized flag. I am not a huge fan of the inconsistency - so let me know if you think I should change this. I did it this way to reduce API calls on applicationHistory page.

Ofmcc 5412 ee updates

---

backend/src/components/files.js
frontend/src/components/messages/RequestConversations.vue

Create a way for business to be able to send attachments to clients

---

frontend/src/services/applicationService.js
frontend/src/views/applications/ApplicationsHistoryView.vue

Add cancelled and ineligble applications to application history view

---

backend/src/components/user.js
frontend/src/components/account-mgmt/ManageUserDialog.vue
frontend/src/views/account-mgmt/ManageUsersView.vue

Removed inactive facilities from chips and dropdown in the edit pop-up
Removed inactive facilities from the list under the "view" button
https://eccbc.atlassian.net/browse/OFMCC-1119

OFMCC- 1119 updates to show active facilities only

---

tools/openshift/backend.deployment.yaml
tools/openshift/frontend-tls.deployment.yaml
tools/openshift/frontend.deployment.yaml

This should let us deploy from branches without running into the deployment matchlabel immutability error

fix: remove branch from matchlabels

---

frontend/src/components/funding/FundingAllocationTab.vue

https://eccbc.atlassian.net/browse/OFMCC-7286
After further discussion the following has been decided:
**Remove :** Banner under Search Facility title that says “Note: If the facility you're looking for does not appear in the dropdown list, that facility may not have an active signed OFM funding agreement.”
**Keep:**
- “Facility Search” title added above search facility drop down menu
- Conditional wording when the organization has no active signed funding agreement, everything below “Search Facility” will not be shown and there will be a banner that says “No Active Funding Agreement Found: This organization currently does not have an active signed OFM funding agreement.”

removed banner for facility filter

---

frontend/src/views/applications/ApplicationsHistoryView.vue

1. Added a custom fixed height at med and lg/xl resolutions so the cards are matched in height and don’t take up too much space
2. Tweaked text/button spacing to accommodate fixed height without taking up more vertical screen space
3. I didn’t tweak the mobile (xs/s) layout since the cards stack vertically and having a consistent height isn’t required

Fixed card alignment.

---

frontend/src/views/HelpView.vue

Added NEW permalink for 2025 applicant guide as the old one can't be repurposed.

OFMCC-7704 - The Final Chapter
