- frontend/.dockerignore
- frontend/.env
- frontend/Caddyfile
- frontend/Dockerfile
- frontend/README.md
Added frontend docker resources.
> Updated backend docker resources.

- .github/workflows/deploy-to-openshift-frontend-dev.yml
- frontend/src/components/Home.vue
- tools/openshift/frontend.dc.yaml
Frontend now deploys to OpenShift.
Volumes aren't required for now and have been commented out.
Host name is just generated for now.
> Add frontend workflow and deployment config

- frontend/src/App.vue
- frontend/src/components/TheEnvBar.vue
- frontend/src/components/TheMenu.vue
- frontend/src/components/ui/AppMenuItem.vue
> Added initial menu.

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/notifications/NotificationsTab.vue
- frontend/src/main.js
- frontend/src/stores/notifications.js
- frontend/src/views/MessagingView.vue
- frontend/yarn.lock
These changes fix the original issues reported from QA, as well improves upon the UI in some small areas (i.e. read/unread buttons and headers).
FYIs:
- I found a new bug that can occur when updating sorted data.
- You'll notice i increased the vue and vuetify versions...  as per my mail on the subject but i rolled that back in last commit as my changes still work. Still think we should upgrade though based on the fact some vuetify doc examples do not work with our versions.
- On MessagingVue I needed to change the font size on v-badge/v-tab to make it position reasonably for both single and double digit unread counts. I could not find a way to do it without using the 'deep selector', applying a simple style would not work. if 3 digits unread count the v-badge will spill into next tab …
> Qafixes ofmcc 251 view notifications

- frontend/src/components/messages/MessagesTab.vue
Update Message page to use vDataTableVirtual and update UI to match with Notification tab.
> OFMCC-364 - replace vDataTable with vDataTableVirtual

- frontend/src/components/notifications/NotificationsTab.vue
Bug fix i found testing on dev. After this verification in dev, it will be ready for QA.
> Fixed bug in header/body checkbox processing when marking read/unread.

- backend/src/components/message.js
- frontend/src/components/messages/NewRequestDialog.vue
OFMCC-646 - bug fix for being unable to submit request when some facilities are not selected
> OFMCC-646 - bug fix for being unable to submit request when some facilities are not selected

- backend/src/components/message.js
- backend/src/routes/message.js
- backend/src/util/common.js
- backend/src/util/constants.js
- backend/src/util/mapping/Mappings.js
- backend/yarn.lock
- frontend/src/components/TheMenu.vue
- frontend/src/components/messages/AssistanceRequestTable.vue
- frontend/src/components/messages/MessagesTab.vue
- frontend/src/components/messages/NewRequestDialog.vue
- frontend/src/components/notifications/NotificationsTab.vue
- frontend/src/components/ui/AppDialog.vue
- frontend/src/main.js
- frontend/src/stores/messages.js
- frontend/src/stores/notifications.js
- frontend/src/utils/constants.js
- frontend/src/views/MessagingView.vue
- frontend/yarn.lock
OFMCC 380 - list requests & OFMCC 589 - display portal status base on CRM status
> OFMCC 380 - list requests, & OFMCC 589 - display portal status base on CRM status

- frontend/src/components/messages/NewRequestDialog.vue
- frontend/src/components/messages/ReplyRequestDialog.vue
- frontend/src/components/ui/AppLabel.vue
- Default facility to current facility
- Added Select All capability
- Switched facility select to use chips
- Added standard modal label
> Ofmcc 658 add request single facility

- backend/src/components/notification.js
Update getNotifications query to only include emails with statecode equals to 1 (Completed)
> ofmcc-405 - update getNotifications query to only include emails with statecode equals to 1 (Completed)

- backend/src/app.js
- backend/src/components/applications.js
- backend/src/routes/applications.js
- backend/src/util/mapping/Mappings.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/plugins/vuetify.js
- frontend/src/services/applicationService.js
- frontend/src/utils/constants.js
- frontend/src/utils/format.js
- frontend/src/views/ApplicationsView.vue
Add Applications table to ApplicationsView
> OFMCC-850 - Application start page

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/TheNavBar.vue
- frontend/src/main.js
Updated vuetify.
Fixed audit issues on frontend.
> Upgrade to vuetify 3.4.x

- frontend/src/App.vue
- frontend/src/components/TheHeader.vue
- frontend/src/components/messages/MessagesTab.vue
- frontend/src/stores/auth.js
- frontend/src/views/MinistryLoginView.vue
Fix minor UI bugs and hide Messaging icon from Internal site
> ofmcc-1023 - fix minor UI bugs and hide Messaging icon from Internal site

- frontend/src/assets/css/main.css
- frontend/src/components/settings/ManageUserDialog.vue
- frontend/src/plugins/vuetify.js
Renamed theme and changed disabled opacity.
> Disabled role/facility if editing own account.

- frontend/src/components/applications/ApplicationNavBar.vue
ofmcc-852-853-855 - Minor bug fix for Application NavBar checkbox
> ofmcc-852-853-855 - minor bug fix for Application NavBar checkbox

- frontend/src/views/applications/SelectFacilityView.vue
ofmcc-852 - preselect facility when there is only 1 facility
> ofmcc-852 - preselect facility when there is only 1 facility

- backend/src/components/user.js
- backend/src/routes/user.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/settings/DeactivateUserDialog.vue
- frontend/src/views/SettingsView.vue
> ofmcc-729 - deactivate user

- backend/src/components/applications.js
- backend/src/components/facilities.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/applications/ContactInfo.vue
- frontend/src/components/facilities/FacilityInfo.vue
- frontend/src/services/facilityService.js
- frontend/src/stores/applications.js
- frontend/src/views/account-mgmt/ManageFacilityView.vue
- frontend/src/views/applications/FacilityDetailsView.vue
- frontend/src/views/applications/StaffingView.vue
-Added primary contact and secondary contact to Facility Details
- Updated FacilityInfo to receive facility object as a prop instead of facilityId
- Updated Expense Authority/Primary Contact in getFacility/getFacilityContacts
- Update ManageUserFacilities to have a single primary contact instead of multiple primary contacts
> ofmcc-856 - Add primary contact and secondary contact to Facility Details

- backend/src/components/applications.js
- backend/src/components/organizations.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/organizations/OrganizationInfo.vue
- frontend/src/components/ui/AppButton.vue
- frontend/src/components/ui/AppNavButtons.vue
- frontend/src/views/MessagingView.vue
- frontend/src/views/account-mgmt/AccountMgmtView.vue
- frontend/src/views/account-mgmt/ManageFacilityView.vue
- frontend/src/views/account-mgmt/ManageOrganizationView.vue
- frontend/src/views/account-mgmt/ManageUsersView.vue
- frontend/src/views/applications/ApplicationsHistoryView.vue
- frontend/src/views/applications/FacilityDetailsView.vue
- frontend/src/views/applications/SelectFacilityView.vue
- Add org binding, provider type, ownership to createApplication
- Update OrganizationInfo to receive organization object instead of organizationId
- Minor UI update to navigation button (change left/arrow icon)
> ofmcc-1048 - add some fields to createApplication payload

- frontend/src/components/ui/AppDocumentUpload.vue
- frontend/src/utils/file.js
- frontend/src/views/account-mgmt/ManageUsersView.vue
Fix bugs for document uploads:
- https://eccbc.atlassian.net/browse/OFMCC-1433: unable to upload file with file extension .HEIC
- Only able to see maximum 10 files in Uploaded documents
> ofmcc-1433 - fix bugs for upload documents and mange user facility table

- backend/src/components/applications.js
- backend/src/util/mapping/Mappings.js
- frontend/src/stores/applications.js
- frontend/src/views/applications/FacilityDetailsView.vue
Add expense authority to Facility Details page
> ofmcc-1320 - add expense authority to Facility Details page

- frontend/src/views/applications/DeclareSubmitView.vue
- frontend/src/views/applications/ServiceDeliveryView.vue
CRM team updated the field type of Licence/Application declaration, so we need to make the same update. https://eccbc.atlassian.net/browse/OFMCC-1655
> Ofmcc 1839 - Update Application/Licence declaration

- backend/src/util/mapping/Mappings.js
- frontend/src/components/supp-allowances/IndigenousProgrammingAllowance.vue
- frontend/src/components/supp-allowances/SupportNeedsProgrammingAllowance.vue
- frontend/src/components/supp-allowances/TransportationAllowance.vue
- frontend/src/services/documentService.js
- frontend/src/views/supp-allowances/SupplementaryFormView.vue
also has UI wording updates from ticket 1834
https://eccbc.atlassian.net/browse/OFMCC-1834
> Ofmcc 1625 transport funding

- frontend/src/components/TheHeader.vue
- frontend/src/components/messages/AssistanceRequestTable.vue
- frontend/src/components/notifications/NotificationsTab.vue
- frontend/src/plugins/vuetify.js
- frontend/src/views/ReportingView.vue
- frontend/src/views/UnAuthorizedPageView.vue
- frontend/src/views/UnAuthorizedView.vue
Fixed layout issue with Notifications.
> Updated red usage to BC Gov standard.

- frontend/src/assets/css/main.css
- frontend/src/components/TheFooter.vue
- frontend/src/components/TheHeader.vue
- frontend/src/components/messages/AssistanceRequestTable.vue
- frontend/src/views/ReportingView.vue
- frontend/src/views/UnAuthorizedPageView.vue
- frontend/src/views/UnAuthorizedView.vue
Simplified usage of standard red/green.
> Added Territorial Acknowledgement to Footer.

- frontend/src/components/messages/NewRequestDialog.vue
- frontend/src/components/messages/ReplyRequestDialog.vue
- frontend/src/utils/constants.js
- frontend/src/views/account-mgmt/ManageOrganizationView.vue
- frontend/src/views/applications/OperatingCostsView.vue
- Used standard message
- Updated New Request message to use failure not warning since the message now applies specifically to the upload which failed
> Standardized virus scan message

- frontend/src/components/messages/NewRequestDialog.vue
Noticed during DEV verification label was wrapping so adjusted margins to accommodate. Re-tested for all resolution sizes.
> Ofmcc 2154 show facility for licence cr

- backend/src/components/lookup.js
- backend/src/util/mapping/Mappings.js
- frontend/src/stores/app.js
- frontend/src/stores/auth.js
- frontend/src/utils/constants.js
- frontend/src/views/applications/ApplicationsHistoryView.vue
- frontend/src/views/applications/SelectFacilityView.vue
Changes in this PR:
- Add Application Intake validation to Application History view: only enable "Add OFM Application" if there is at least 1 facility allowed to apply for OFM application.
- Update the facility dropdown list in Select Facility View to only show facilities allowed to apply for OFM application
Note: A facility can apply for a core application if there is an Open Intake or it is in the allowed facility list of a Limited Intake
> OFMCC-1661 - Application Intake Window

- backend/src/components/facilities.js
- frontend/src/components/account-mgmt/EditFacilityContacts.vue
- frontend/src/views/account-mgmt/ManageFacilityView.vue
- frontend/src/views/account-mgmt/ManageUsersView.vue
Excluded deleted records.
Handled null firstName.
Simplified EditFacilityContacts name display.
> OFMCC-1791 - Primary Contact dropdown fixes

- backend/src/routes/reports.js
- frontend/src/components/reports/PendingReportsTab.vue
- frontend/src/router/index.js
- frontend/src/views/HomeView.vue
- frontend/src/views/reports/SurveyView.vue
Secured reporting permissions.
Added stub code for delete.
> OFMCC-1829 - Permissions for Reporting

- backend/src/components/fundingAgreements.js
- backend/src/routes/fundingAgreements.js
- backend/src/util/mapping/Mappings.js
- frontend/src/router/index.js
- frontend/src/services/fundingAgreementService.js
- frontend/src/utils/constants.js
- frontend/src/views/funding/FundingConfirmationView.vue
- frontend/src/views/funding/FundingOverviewView.vue
- frontend/src/views/funding/FundingView.vue
Sign and Submit the funding agreement. 
Please note - the Funding Agreement GUID is still hardcoded on FundingOverviewView.vue - and this will be changed upon the completion of Johnathan's work. 
Also includes ticket 2040 (update the status of FA)
> Ofmcc 2039 sign funding agreement

- frontend/src/assets/css/reset.css
- frontend/src/components/applications/review/OperatingCostsSummary.vue
- frontend/src/stores/applications.js
- frontend/src/utils/constants.js
- frontend/src/views/applications/OperatingCostsView.vue
UI updates and renaming of a heading
> Ofmcc 1403 update doc upload ofm

- backend/src/components/applications.js
- backend/src/routes/applications.js
- backend/src/util/mapping/Mappings.js
- frontend/src/assets/css/main.css
- frontend/src/components/applications/StaffingCertificateInput.vue
- frontend/src/components/applications/review/StaffingSummary.vue
- frontend/src/components/ui/AppMissingInfoError.vue
- frontend/src/services/applicationService.js
- frontend/src/stores/applications.js
- frontend/src/utils/common.js
- frontend/src/utils/constants.js
- frontend/src/views/applications/ApplicationView.vue
- frontend/src/views/applications/ApplicationsHistoryView.vue
- frontend/src/views/applications/StaffingView.vue
Summary of this ticket:
- Add Employee Certificate input to Staffing view and Staffing Summary view
- Add some validations for Employee Certificate: The provider must provide ECE/ECEA certificates for all employees (the number of staff and the number of certificates must match, and there must be no duplicate Initials or Certificate Numbers)
- The max length of Initials is 4, and the max length of Certificate Numbers is 6. Certificate Numbers is a number field
> OFMCC-2048 - add Employee Certificates to Staffing page in Core Application

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/TheEnvBar.vue
- frontend/src/components/TheHeader.vue
- frontend/src/main.js
- frontend/src/router/index.js
- frontend/src/stores/app.js
- Fixed issue with system error on backend startup. Even though lookup code was moved from App.vue to main.js the router was still being initiated before the lookup was done. Moved router init.
- Added error handling for backend failures.
- Code cleanup.
> Startup fixes

- backend/src/components/fundingAgreements.js
- backend/src/routes/user.js
- backend/src/util/common.js
- backend/src/util/constants.js
- frontend/src/router/index.js
- frontend/src/services/fundingAgreementService.js
- frontend/src/services/organizationService.js
- frontend/src/services/userService.js
- frontend/src/utils/constants/permissions.js
- frontend/src/views/account-mgmt/AccountMgmtView.vue
- frontend/src/views/account-mgmt/ManageUsersView.vue
- frontend/src/views/funding/FundingOverviewView.vue
Added permissions for Manage Users View.
Refactored fundingAgreement queries to improve API and simplify code.
> OFMCC-3504 - Manage Users View security

- frontend/src/views/reports/ReportingView.vue
Update statuses for Submitted report response's status in Reporting View
> ofmcc-3825 - Update statuses for Submitted report response's status in Reporting View

- frontend/src/components/messages/NewRequestDialog.vue
- frontend/src/components/messages/RequestConversations.vue
Added support for html messages in conversations.
Fixed bug with org updates being sent in non-Assistance Request.
> OFMCC-3722 - HTML appearing in message body

- backend/src/components/facilities.js
- backend/src/util/mapping/Mappings.js
- frontend/src/stores/auth.js
- frontend/src/views/applications/ApplicationsHistoryView.vue
- frontend/src/views/applications/SelectFacilityView.vue
Add CCOF enrolment check for adding core application
> OFMCC-2053 - Add CCOF enrolment check for adding core application

- backend/src/app.js
- backend/src/routes/auth.js
> Update logout URL

- backend/src/app.js
- backend/src/components/lookup.js
- frontend/src/components/TheHeader.vue
- frontend/src/router/index.js
- frontend/src/stores/auth.js
- frontend/src/views/HomeView.vue
Added support for Impersonate on frontend and backend.
Added some permissions to improve user experience for Impersonate.
Updated roles query to exclude deactivated records.
Handled TODOs in router.
Minor bug fix for title colour at xs resolution.
> OFMCC-2280 Impersonate permissions

- frontend/src/views/applications/ApplicationView.vue
First name is optional in Dynamics and "null 202" was showing in the dropdown. Applied same fixed used in ManageFacilityView.vue.
> Fix for null firstName.

- .github/workflows/deploy-to-openshift-backend-dev.yml
- .github/workflows/deploy-to-openshift-backend-test.yml
- .github/workflows/deploy-to-openshift-backend-uat.yml
- backend/src/app.js
- backend/src/components/auth.js
- backend/src/components/utils.js
- backend/src/config/index.js
- backend/src/routes/auth.js
- frontend/src/router/index.js
- frontend/src/views/MinistryLogoutView.vue
- tools/config/update-configmap.sh
- Updated code to handle new custom realm which uses a single client
- Made idphint configurable
- Added logout screen for IDIR users (code to be refactored and restyle in OFMCC-4175)
> Ofmcc 2157 sso updates

- backend/src/app.js
- backend/src/components/facilities.js
- backend/src/components/fundingAgreements.js
- backend/src/middlewares/validateExpenseAuthority.js
- backend/src/middlewares/validatePermission.js
- backend/src/routes/fundingAgreements.js
- backend/src/routes/licences.js
- backend/src/routes/payments.js
- backend/src/util/constants.js
- frontend/src/router/index.js
- frontend/src/stores/auth.js
- frontend/src/utils/constants/permissions.js
- frontend/src/views/HomeView.vue
- frontend/src/views/funding/FundingOverviewView.vue
- Removed Documents from Home Page
- Added ability to hide routes
- Added funding security
- Added missing licenses security
- Updated validatePermission to accept a list of permissions
- Added backend validation for signing funding agreement
> OFMCC-1830 - Funding permissions

- frontend/src/views/account-mgmt/ManageUsersView.vue
Update cloning to fix bug where nested Role was updated.
> OFMCC-4393 - Role lost after clicking Edit

- backend/src/components/user.js
Fixed role handling by updating request structure.
> OFMCC-4394 - Deactivate user not removing role

- frontend/src/components/reports/PendingReportsTab.vue
- frontend/src/components/reports/ReportingHistoryTab.vue
- frontend/src/views/applications/ApplicationView.vue
- frontend/src/views/applications/OperatingCostsView.vue
Bugs're fixed in this PR:
- Monthly Report - Alerts, Title, and Status columns are not sortable in Report tables
- OFMCC-1588
- OFMCC-3423
> OFMCC-1588 - Fix Application and MR bugs

- .github/workflows/deploy-to-openshift-frontend-dev.yml
- .github/workflows/deploy-to-openshift-frontend-uat.yml
> fix: whitespace escapes

- frontend/src/components/notifications/NotificationDetails.vue
Fix notification formatting for html CRM notifications.
Had to remove scoped since it wasn't playing nicely.
> OFMCC-3095 - Notification formatting fix

- backend/src/app.js
- backend/src/config/index.js
- backend/src/util/redis/cache-helper.js
- backend/src/util/redis/redis-client.js
- tools/config/update-configmap.sh
> Implement Redis for session storage

- backend/src/config/index.js
- backend/src/util/redis/redis-client.js
> fix: redis env name/value type

- backend/src/routes/user.js
- frontend/src/components/account-mgmt/ManageUserDialog.vue
- frontend/src/views/account-mgmt/ManageUsersView.vue
- frontend/src/views/applications/ApplicationsHistoryView.vue
Security update to use the more correct permission.
Bug fixes for missing facilityName.
> Security update and small bug fix.

- backend/src/util/mapping/Mappings.js
- frontend/src/components/applications/ApplicationNavBar.vue
- frontend/src/components/applications/review/OperatingCostsSummary.vue
- frontend/src/components/ui/AppDocumentUpload.vue
- frontend/src/stores/applications.js
- frontend/src/utils/constants.js
- frontend/src/views/applications/ApplicationView.vue
- frontend/src/views/applications/OperatingCostsView.vue
Changes in this PR:
- Add Arm Length question to Application's Operating Cost section
- Application Nav bar enhancement and simplify its logic
> ofmcc-3485 - add arm length to application, refactor Application Nav Bar

- .github/workflows/create-git-and-image-tag.yml
- .github/workflows/deploy-to-openshift-backend-dev.yml
- .github/workflows/deploy-to-openshift-backend-test.yml
- .github/workflows/deploy-to-openshift-backend-uat.yml
- .github/workflows/deploy-to-openshift-frontend-dev.yml
- .github/workflows/deploy-to-openshift-frontend-test.yml
- .github/workflows/deploy-to-openshift-frontend-uat.yml
The goal is to improve deployment stability by assuming that oc will respect semver.
> feat: pin some more software

- frontend/src/components/TheHeader.vue
- frontend/src/router/index.js
- frontend/src/views/HelpView.vue
- frontend/src/views/HomeView.vue
- Add help and home icons to header
- Update layout for responsiveness
- Clean up styles
- Rename "Resources" to "Help"
> OFMCC-4741 - Header updates

- frontend/src/router/index.js
- Updated error handling for unauthorized (not registered) users
- Code cleanup for consistent usage of next/return
> OFMCC-4817 - Error handling updates

- frontend/src/components/messages/NewRequestDialog.vue
- frontend/src/views/account-mgmt/ManageFacilityView.vue
- frontend/src/views/account-mgmt/ManageOrganizationView.vue
Updated to refresh on submit not on close confirmation.
> Ofmcc 3478 cr refresh issue

- backend/src/components/user.js
Updated validation to account for username update. User should get Unauthorized Access to they have to contact support to get their username updated.
> OFMCC-5015 -  BCeID username change

- frontend/src/views/LoginView.vue
Simplified layout and updated login text.
> OFMCC-4959 - Login updates

- .github/workflows/deploy-to-openshift-frontend-dev.yml
- .github/workflows/deploy-to-openshift-frontend-test.yml
- .github/workflows/deploy-to-openshift-frontend-uat.yml
Updated form URL. Prod will be updated in a separate branch as it's under development.
> OFMCC-4194 - Irregular Expense Form URL

- frontend/src/assets/css/main.css
- frontend/src/components/supp-allowances/TransportationAllowance.vue
- frontend/src/components/ui/AppSimpleCard.vue
- frontend/src/views/HomeView.vue
- frontend/src/views/account-mgmt/AccountMgmtView.vue
- frontend/src/views/applications/ApplicationsHistoryView.vue
Moved to a card based layout.
Added security.
Fixed HomeView style.
> OFMCC-4844 - Final content for Account Management

- frontend/src/components/account-mgmt/EditFacilityContacts.vue
- frontend/src/components/account-mgmt/UnableToSubmitCrDialog.vue
- frontend/src/components/applications/YearlyOperatingCost.vue
- frontend/src/components/facilities/FacilityFilter.vue
- frontend/src/components/funding/FundingAgreementsTab.vue
- frontend/src/components/funding/PaymentRecordsTab.vue
- frontend/src/components/messages/RequestConversations.vue
- frontend/src/components/organizations/OrganizationInfo.vue
- frontend/src/components/reports/PendingReportsTab.vue
- frontend/src/components/reports/ReportingHistoryTab.vue
- frontend/src/components/ui/AppButton.vue
- frontend/src/components/ui/AppDialog.vue
- frontend/src/components/ui/AppDocumentUpload.vue
- frontend/src/utils/constants.js
- frontend/src/views/account-mgmt/ManageFacilityView.vue
- frontend/src/views/account-mgmt/ManageOrganizationView.vue
- frontend/src/views/account-mgmt/ManageUsersView.vue
- frontend/src/views/applications/ApplicationsHistoryView.vue
- frontend/src/views/applications/OperatingCostsView.vue
- frontend/src/views/funding/FundingView.vue
There are only UI/UX fixes in this PR:
- OFMCC-3122
- OFMCC-4778
- OFMCC-4841
- OFMCC-4916
- OFMCC-4917
- OFMCC-4931
> Ofmcc 4778 UI changes

- backend/src/util/mapping/Mappings.js
- frontend/src/components/applications/review/ServiceDeliverySummary.vue
- frontend/src/components/applications/review/StaffingSummary.vue
- frontend/src/components/licences/LicenceDetails.vue
- frontend/src/components/supp-allowances/SupportNeedsProgrammingAllowance.vue
- frontend/src/router/index.js
- frontend/src/services/applicationService.js
- frontend/src/stores/app.js
- frontend/src/stores/applications.js
- frontend/src/utils/constants.js
- frontend/src/utils/format.js
- frontend/src/utils/rules.js
- frontend/src/views/applications/DeclareSubmitView.vue
- frontend/src/views/applications/FacilityDetailsView.vue
- frontend/src/views/applications/StaffingView.vue
Changes in this PR:
- OFMCC-5049 - add union and cssea questions to Application
- OFMCC-5252 - update Application's declaration wording
- OFMCC-5115 - fix scroll behavior when navigating between Application's pages
> Ofmcc 5049 ccsea union questions

- backend/src/components/fundingAgreements.js
- frontend/src/components/account-mgmt/ManageUserDialog.vue
- frontend/src/components/messages/RequestConversations.vue
- frontend/src/utils/rules.js
- frontend/src/views/applications/StaffingView.vue
Changes in this PR:
OFMCC-5123
OFMCC-5312
> Ofmcc 5123 blank first name

- frontend/src/views/account-mgmt/ManageUsersView.vue
Fixed issue with bad migrated data.
> Small ManageUsersView bug

- backend/src/app.js
- backend/src/config/index.js
- frontend/Caddyfile
- tools/openshift/backend.dc.yaml
- tools/openshift/frontend.dc.yaml
- Added Strict to Route cookies.
- Added Lax to ofm_cookies (Strict causes issues on post login redirect)
- Tightened up CSP settings
> OFMCC-5351 - CSP/Cookie fixes

- backend/src/components/applications.js
- backend/src/components/documents.js
- backend/src/components/fundingAgreements.js
- backend/src/components/utils.js
- backend/src/routes/applications.js
- backend/src/routes/documents.js
- backend/src/routes/fundingAgreements.js
- backend/src/routes/payments.js
Note, the issues identified in the WAVA scan were not related to integer overflow errors, but poor validation/error handling. The following fixes were made to identified endpoints:
- Pass Dynamics 4** errors onto the client instead of returning a 500
- Improve validation for stateCode/statusCode and certain UUIDs
> OFMCC-5273 - WAVA Integer overflow

- backend/src/components/reports.js
- frontend/src/components/funding/FundingSearchCard.vue
- frontend/src/components/reports/ReportingSearchCard.vue
- frontend/src/components/ui/AppDateInput.vue
- frontend/src/main.js
- frontend/src/utils/format.js
- frontend/src/views/applications/FacilityDetailsView.vue
Change in this PR:
- Update Get pending reports query to use submittedBy field instead of submittedOn field
- Replace v-date-input with AppDateInput component
> ofmcc-5402 - fix report banner bug, add AppDateInput component

- frontend/src/components/supp-allowances/TransportationAllowance.vue
- frontend/src/components/supp-allowances/TransportationSummary.vue
- frontend/src/components/ui/AppDateInput.vue
- frontend/src/utils/format.js
- frontend/src/utils/rules.js
- frontend/src/views/funding/FundingView.vue
- frontend/src/views/supp-allowances/SupplementaryAllowanceView.vue
- frontend/src/views/supp-allowances/SupplementaryFormView.vue
Small change in SuppAllowanceView fixes a bug where the view would not re load when selecting a different facility from the dropdown.
> Ofmcc 4772 transport backdate

- frontend/src/components/TheHeader.vue
- frontend/src/router/index.js
- frontend/src/views/HomeView.vue
> OFMCC-5406 - Remove help

- .github/workflows/deploy-to-openshift-backend-dev.yml
- .github/workflows/deploy-to-openshift-backend-efx.yml
- .github/workflows/deploy-to-openshift-backend-prod.yml
- .github/workflows/deploy-to-openshift-backend-test.yml
- .github/workflows/deploy-to-openshift-backend-uat.yml
- .github/workflows/deploy-to-openshift-frontend-dev.yml
- .github/workflows/deploy-to-openshift-frontend-efx.yml
- .github/workflows/deploy-to-openshift-frontend-prod.yml
- .github/workflows/deploy-to-openshift-frontend-test.yml
- .github/workflows/deploy-to-openshift-frontend-uat.yml
> Add EFX environment

- frontend/src/components/funding/FundingAgreementsTab.vue
- frontend/src/components/messages/MessagesTab.vue
- frontend/src/components/messages/RequestConversations.vue
- frontend/src/components/notifications/NotificationDetails.vue
- frontend/src/components/notifications/NotificationsTab.vue
- frontend/src/components/reports/PendingReportsTab.vue
- frontend/src/components/reports/ReportingHistoryTab.vue
- frontend/src/components/ui/AppButton.vue
- frontend/src/utils/constants.js
- frontend/src/views/MessagingView.vue
Updated default tab from Notifications to Messages.
Changed button styling on all buttons in Messages/Notifications.
General button standardization for "small" buttons.
ESlint cleanup.
> OFMCC-5687 - Messages UI updates

- frontend/src/components/TheHeader.vue
- frontend/src/views/HomeView.vue
Added temporary help links.
Didn't bother with constants (or ideally config.js) since this will be replaced in 1.1 with the help screen.
> OFMCC-5417 - Add Help/Resources link

- backend/src/routes/user.js
- frontend/src/components/account-mgmt/ManageUserDialog.vue
- frontend/src/views/account-mgmt/ManageFacilityView.vue
- frontend/src/views/applications/FacilityDetailsView.vue
Made firstName optional on screen and backend.
> OFMCC-5313 - Contact first name optional

- CHANGELOG.md
- frontend/src/components/TheHeader.vue
- frontend/src/views/HomeView.vue
Updated tile wording.
Updated CHANGELOG in prep for release 1.0.1.
> Ofmcc 5417 help resources link

- frontend/src/components/TheFacilityHeader.vue
- frontend/src/views/HomeView.vue
- testing/README.md
- testing/cypress/e2e/1-portal-and-crm-login-and-security/portal_login.cy.js
Remove facility from org header.
Test updates.
> OFMCC-5427 - Remove Facility name from Home Page

- frontend/src/assets/css/main.css
- frontend/src/components/supp-allowances/IndigenousProgrammingAllowance.vue
- frontend/src/components/supp-allowances/SupportNeedsProgrammingAllowance.vue
- frontend/src/utils/constants/suppConstants.js
- frontend/src/views/supp-allowances/SupplementaryFormView.vue
- frontend/src/views/supp-allowances/SupplementarySubmitView.vue
- Added UI categories for ticket https://eccbc.atlassian.net/browse/OFMCC-5753
- Additionally - did a bit of refactoring to add PANELS objects into a constants file. With that - I also changed the logic on Supplementary Submit Page to check the models for completed applications - instead of adding that information to the panel object 
- Small code changes to update props to snake-case and other linter recommendations
> Ofmcc 5753 supp apps UI update

- backend/src/routes/applications.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/applications/ApplicationHeader.vue
- frontend/src/components/applications/ApplicationNavBar.vue
- frontend/src/components/applications/EligibilityNotificationDialog.vue
- frontend/src/components/ui/AppDialog.vue
- frontend/src/components/ui/AppYesNoRadioGroup.vue
- frontend/src/router/index.js
- frontend/src/services/applicationService.js
- frontend/src/stores/applications.js
- frontend/src/utils/constants.js
- frontend/src/views/applications/ApplicationView.vue
- frontend/src/views/applications/DeclareSubmitView.vue
- frontend/src/views/applications/EligibilityView.vue
- frontend/src/views/applications/FacilityDetailsView.vue
- frontend/src/views/applications/ReviewApplicationView.vue
- frontend/src/views/applications/ServiceDeliveryView.vue
Add Application Eligibility and some validations
UI update - application header
> OFMCC-5293 - Application Eligibility

- backend/src/util/mapping/Mappings.js
- frontend/src/components/applications/RentLeaseInformation.vue
- frontend/src/components/applications/YearlyFacilityCost.vue
- frontend/src/components/applications/YearlyOperatingCost.vue
- frontend/src/components/applications/review/OperatingCostsSummary.vue
- frontend/src/components/applications/review/YearlyFacilityCostSummary.vue
- frontend/src/components/applications/review/YearlyOperatingCostSummary.vue
- frontend/src/stores/applications.js
- frontend/src/utils/constants.js
- frontend/src/utils/format.js
- frontend/src/views/applications/OperatingCostsView.vue
- Update the labels of Yearly Operating Cost
- Add Rent Lease Information
- Refactor OperatingCost view to make it cleaner.
> OFMCC-5295 - Update Application's Operating Cost

- backend/src/components/organizations.js
- backend/src/middlewares/validateFacility.js
Fixed 403 with read only facilities by also validating org facilities.
> OFMCC-6078

- frontend/src/components/TheHeader.vue
- frontend/src/router/index.js
- frontend/src/views/HomeView.vue
Temporarily remove help content until approved.
> Removed help content.

- selenium-testing/config.properties.template
- selenium-testing/pom.xml
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/PageFactory_CRM/CRMHomePage.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/PageFactory_CRM/CRMSignInCredentialPage.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/PageFactory_CRM/LicenseDetailsPage.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/PageFactory_CRM/ServiceDeliveryDetailsPage.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/PageFactory_Portal/PortalHomePage.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/PageFactory_Portal/PortalImpersonatePage.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/PageFactory_Portal/PortalIrregularExpenseApplicationsDetails.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/PageFactory_Portal/PortalMessagesAndNotificationsPage.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/PageFactory_Portal/PortalSignInFirstPage.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/tests/BaseTest.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/tests/crm/CRMAddLicenceToFacility.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/tests/portal/PortalCreateIrregularExpenseApplication.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/tests/scripting/ContactBCeIDScript.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/tests/scripting/SmokeTestScript.java
Implemented:
[https://eccbc.atlassian.net/browse/OFMCC-6222](https://eccbc.atlassian.net/browse/OFMCC-6222)
- Made minor code changes
- Created Smoke test script
> OFMCC-6222 - QA Auto - Smoke test script

- selenium-testing/.gitignore
- selenium-testing/cicd/cicd-script.bat
- selenium-testing/config.properties.template
- selenium-testing/pom.xml
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/PageFactory_CRM/CRMHomePage.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/PageFactory_CRM/CRMSignInCredentialPage.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/PageFactory_Portal/InternalPortalImpersonatePage.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/PageFactory_Portal/InternalPortalSignInFirstPage.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/PageFactory_Portal/PortalSignInCredentialPage.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/tests/BaseTest.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/tests/crm/CRMAddLicenceToFacility.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/tests/crm/CRMCreateIrregularExpenseApplication.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/tests/crm/CRMCreateOrganizationContactFacility.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/tests/crm/CRMLogin.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/tests/portal/PortalCreateAllowanceApplication.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/tests/portal/PortalCreateApplication.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/tests/portal/PortalCreateIrregularExpenseApplication.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/tests/portal/PortalLogin.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/tests/scripting/SmokeTestScript.java
- selenium-testing/src/test/resources/testNG.xml
> Smoke test script and some changes to support zephyr integration

- .github/workflows/create-git-and-image-tag.yml
- .github/workflows/deploy-to-openshift-backend-efx.yml
- .github/workflows/deploy-to-openshift-backend-prod.yml
- .github/workflows/deploy-to-openshift-backend-test.yml
- .github/workflows/deploy-to-openshift-backend-uat.yml
- .github/workflows/deploy-to-openshift-frontend-efx.yml
- .github/workflows/deploy-to-openshift-frontend-prod.yml
- .github/workflows/deploy-to-openshift-frontend-test.yml
- .github/workflows/deploy-to-openshift-frontend-uat.yml
Added explicit tag selection and input summary to workflows higher than Dev.
Added input summary to tag workflow.
> OFMCC-5835 - Tag selection for builds

- selenium-testing/.gitignore
- selenium-testing/cicd/cicd-script.bat
- selenium-testing/pom.xml
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/tests/BaseTest.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/tests/CustomReporter.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/tests/scripting/SmokeTestScript.java
- selenium-testing/src/test/resources/testNG.xml
Implementation:
- [https://eccbc.atlassian.net/browse/OFMCC-6338](https://eccbc.atlassian.net/browse/OFMCC-6338)
> OFMCC-6338 Custom reporting/integration with JIRA and Zephyr

- frontend/Caddyfile
CSP update to allow data: images to show.
> Added data to image-src.

- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/PageFactory_Portal/PortalFundingAllocationTab.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/PageFactory_Portal/PortalFundingEnvelopeChangeRequest.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/PageFactory_Portal/PortalFundingPage.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/tests/portal/PortalCreateFundingEnvelopeChangeRequest.java
Implements: 
[https://eccbc.atlassian.net/browse/OFMCC-6476](https://eccbc.atlassian.net/browse/OFMCC-6476)
- Added test for Create Funding envelope change request through the funding tile.
> OFMCC-6476-Create Funding Envelope Change Request through Funding Tile

- selenium-testing/cicd/cicd-script.bat
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/tests/BaseTest.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/tests/scripting/SmokeTestScript.java
Implements: 
[https://eccbc.atlassian.net/browse/OFMCC-6338](https://eccbc.atlassian.net/browse/OFMCC-6338)
- Change pointing to repo instead of local
> OFMCC-6338 - Change pointing to repo

- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/PageFactory_Portal/PortalCreateFundingAndPaymentsRequest.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/tests/portal/PortalPaymentsAndFundingRequest.java
Implements 
[https://eccbc.atlassian.net/browse/OFMCC-6477](https://eccbc.atlassian.net/browse/OFMCC-6477)
> OFMCC-6477 - Create a Payments and Funding Request

- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/PageFactory_Portal/PortalCreateFundingAndPaymentsRequest.java
- selenium-testing/src/test/java/ca/bc/gov/ecc/ofm/selenium/v1/tests/portal/PortalPaymentsAndFundingRequest.java
Updated minor fixes for automation
> Updated minor fixes for automation

- frontend/src/views/HelpView.vue
We need to revert  this commit because the uploaded document will not be ready in time for prod deployment.
> Revert "fix: out of date policy & procedures manual"

- frontend/src/components/messages/RequestConversations.vue
Our CSPs don't allow it and we need something that works until we figure it out
> fix: remove PDF in new tab feature

- frontend/src/views/HelpView.vue
Numerous tickets, named in the commits.
> Update a bunch of help and resources links

- backend/src/components/fundingAgreements.js
- backend/src/util/mapping/Mappings.js
- frontend/src/assets/css/main.css
- frontend/src/components/funding/FundingAgreementsTab.vue
- frontend/src/router/index.js
- frontend/src/utils/constants.js
- frontend/src/views/funding/BaseFundingView.vue
- frontend/src/views/funding/FundingConfirmationView.vue
User can decline funding agreement when they have an option to sign the funding agreement.
https://eccbc.atlassian.net/browse/OFMCC-6948
> changes for decline feature

- frontend/src/assets/css/main.css
- frontend/src/utils/constants.js
- frontend/src/views/applications/ApplicationsHistoryView.vue
https://eccbc.atlassian.net/browse/OFMCC-7023
> Added new status to Application and changed the shade of status yellow

- frontend/src/views/HelpView.vue
Added changes to Help and resources as per : https://eccbc.atlassian.net/browse/OFMCC-6471
> updated to help and resources

- frontend/src/views/applications/ApplicationsHistoryView.vue
OFMCC-7335: task is completed.
> OFMCC-7335: task is completed.

- frontend/src/views/supp-allowances/SupplementaryAllowanceView.vue
OFMCC-7362: task is completed.
> OFMCC-7362: task is completed.

- frontend/src/views/HelpView.vue
Ofmcc-7378 new welcome session video
> Ofmcc-7378 new welcome session video

- backend/src/components/payments.js
- backend/src/util/mapping/Mappings.js
- frontend/src/components/funding/PaymentRecordsTab.vue
OFMCC-7154: task is completed.
> OFMCC-7154: task is completed.

- frontend/src/views/supp-allowances/SupplementaryAllowanceView.vue
OFMCC-7392: resolved the back button issue for supplementary application.
> OFMCC-7392: resolved the back button issue.

- frontend/src/views/HomeView.vue
OFMCC-5071: task is completed.
> OFMCC-5071: task is completed.

- frontend/src/views/ImpersonateView.vue
- frontend/src/views/LogoutView.vue
- frontend/src/views/MinistryLoginView.vue
- frontend/src/views/SessionExpiredView.vue
The Impersonate screen was copied from CCOF and doesn’t fit with the current OFM styling. The following updates were made:
- Update card to match default card styling 
- Update button to match default button styling
- Add button disable on loading
- Add responsive layout
Also cleaned up some linter warnings on related screens.
> OFMCC-7409 - Updated Impersonate styling

- backend/src/components/applications.js
- backend/src/components/utils.js
- frontend/src/components/supp-allowances/TransportationSummary.vue
- frontend/src/utils/format.js
- frontend/src/views/supp-allowances/SupplementaryFormView.vue
Ofmcc-7402 : Fix date at top of page to align with the expiry date of the Funding Agreement. 
OFMCC 7443: Add a time zone string to the date field to fix the off by 1 error seen on the retroactive date field in CRM.
> Ofmcc 7443 retro date supp

- frontend/src/views/HomeView.vue
- frontend/src/views/applications/ApplicationsHistoryView.vue
- Fixed existing permissions.
- Added permissions to renewal related actions.
> OFMCC-7567 - Impersonate error

- frontend/src/views/funding/BaseFundingView.vue
Added PPM acknowledgement dialog.
Resolved ESLint and SonarQube warnings.
> OFMCC-7816 - Add PPM Acknowledgement dialog

- frontend/src/views/applications/ApplicationsHistoryView.vue
> fix: ApplicationHistory.vue: Only block draft applications with no intake.

- frontend/eslint.config.mjs
- frontend/src/components/account-mgmt/DeactivateUserDialog.vue
- frontend/src/components/account-mgmt/DuplicateUserDialog.vue
- frontend/src/components/applications/CancelApplicationDialog.vue
- frontend/src/components/licences/LicenceDetails.vue
- frontend/src/components/messages/CloseRequestBanner.vue
- frontend/src/components/messages/ReplyRequestDialog.vue
- frontend/src/components/messages/RequestConversations.vue
- frontend/src/components/organizations/OrganizationHeader.vue
- frontend/src/components/supp-allowances/SupportNeedsProgrammingAllowance.vue
- frontend/src/components/ui/AppDateInput.vue
- frontend/src/components/ui/AppMenuItem.vue
- frontend/src/components/ui/AppTimeInput.vue
- frontend/src/components/ui/AppYesNoInput.vue
- frontend/src/views/account-mgmt/AccountMgmtHomeView.vue
- frontend/src/views/account-mgmt/ManageUsersView.vue
- frontend/src/views/applications/StaffingView.vue
> fix: eslint warnings

- frontend/src/components/ui/AppDocumentUpload.vue
- frontend/src/utils/constants.js
> feat: increase document upload size
